import { ProviderConfig, ModelInfo } from '../types';

export const PROVIDERS: ProviderConfig[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    tagline: 'GPT-4o, o1, o3-mini, GPT-4o-mini',
    iconName: 'Sparkles',
    brandColor: '#10a37f',
    keyPlaceholder: 'sk-proj-... or sk-...',
    keyDocsUrl: 'https://platform.openai.com/api-keys',
    keyFormatRegex: /^sk-[a-zA-Z0-9_\-]{20,}$/,
    keyPrefix: 'sk-',
    requiresKey: true,
    defaultBaseUrl: 'https://api.openai.com/v1',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        provider: 'openai',
        description: 'Flagship omni model, versatile and intelligent',
        contextWindow: 128000,
        inputPrice: 2.50,
        outputPrice: 10.00,
        isVision: true,
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o mini',
        provider: 'openai',
        description: 'Fast, cost-efficient for everyday tasks',
        contextWindow: 128000,
        inputPrice: 0.15,
        outputPrice: 0.60,
        isVision: true,
      },
      {
        id: 'o3-mini',
        name: 'o3-mini',
        provider: 'openai',
        description: 'High-speed reasoning model for coding and math',
        contextWindow: 200000,
        inputPrice: 1.10,
        outputPrice: 4.40,
        isReasoning: true,
      },
      {
        id: 'o1',
        name: 'o1',
        provider: 'openai',
        description: 'Deep reasoning model for complex problem solving',
        contextWindow: 200000,
        inputPrice: 15.00,
        outputPrice: 60.00,
        isReasoning: true,
      },
      {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo',
        provider: 'openai',
        description: 'Previous generation high-intelligence model',
        contextWindow: 128000,
        inputPrice: 10.00,
        outputPrice: 30.00,
        isVision: true,
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    tagline: 'Claude 3.7 Sonnet, Claude 3.5 Sonnet & Haiku',
    iconName: 'BrainCircuit',
    brandColor: '#d97757',
    keyPlaceholder: 'sk-ant-api03-...',
    keyDocsUrl: 'https://console.anthropic.com/settings/keys',
    keyFormatRegex: /^sk-ant-[a-zA-Z0-9_\-]{20,}$/,
    keyPrefix: 'sk-ant-',
    requiresKey: true,
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true, // supported via anthropic-dangerous-direct-browser-access: true
    defaultModels: [
      {
        id: 'claude-3-7-sonnet-20250219',
        name: 'Claude 3.7 Sonnet',
        provider: 'anthropic',
        description: 'Hybrid reasoning model with thinking capabilities',
        contextWindow: 200000,
        inputPrice: 3.00,
        outputPrice: 15.00,
        isReasoning: true,
        isVision: true,
      },
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        provider: 'anthropic',
        description: 'Benchmark leader in coding and reasoning',
        contextWindow: 200000,
        inputPrice: 3.00,
        outputPrice: 15.00,
        isVision: true,
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        provider: 'anthropic',
        description: 'Ultra-fast, responsive intelligence',
        contextWindow: 200000,
        inputPrice: 0.80,
        outputPrice: 4.00,
      },
      {
        id: 'claude-3-opus-20240229',
        name: 'Claude 3 Opus',
        provider: 'anthropic',
        description: 'Deep writing, analysis, and nuanced thinking',
        contextWindow: 200000,
        inputPrice: 15.00,
        outputPrice: 75.00,
        isVision: true,
      },
    ],
  },
  {
    id: 'google',
    name: 'Google Gemini',
    tagline: 'Gemini 2.0 Flash, Gemini 1.5 Pro, Flash Lite',
    iconName: 'Gem',
    brandColor: '#4285f4',
    keyPlaceholder: 'AIzaSy...',
    keyDocsUrl: 'https://aistudio.google.com/app/apikey',
    keyFormatRegex: /^AIzaSy[a-zA-Z0-9_\-]{33}$/,
    keyPrefix: 'AIzaSy',
    requiresKey: true,
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'gemini-3.7-flash',
        name: 'Gemini 3.7 Flash',
        provider: 'google',
        description: 'Next-generation frontier multimodal model with dynamic thinking reasoning',
        contextWindow: 1000000,
        inputPrice: 0.10,
        outputPrice: 0.40,
        isReasoning: true,
        isVision: true,
      },
      {
        id: 'gemini-3.6-flash',
        name: 'Gemini 3.6 Flash',
        provider: 'google',
        description: 'High-speed, high-efficiency intelligence for multimodal tasks',
        contextWindow: 1000000,
        inputPrice: 0.10,
        outputPrice: 0.40,
        isReasoning: true,
        isVision: true,
      },
      {
        id: 'gemini-3.1-pro-preview',
        name: 'Gemini 3.1 Pro Preview',
        provider: 'google',
        description: 'Flagship reasoning, deep coding, and complex multimodal synthesis',
        contextWindow: 2000000,
        inputPrice: 1.25,
        outputPrice: 5.00,
        isReasoning: true,
        isVision: true,
      },
      {
        id: 'gemini-3.1-flash-lite',
        name: 'Gemini 3.1 Flash Lite',
        provider: 'google',
        description: 'Ultra-lightweight, high-throughput cost-effective model',
        contextWindow: 1000000,
        inputPrice: 0.075,
        outputPrice: 0.30,
        isVision: true,
      },
      {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        provider: 'google',
        description: 'Advanced reasoning and long-context multimodal comprehension',
        contextWindow: 2000000,
        inputPrice: 1.25,
        outputPrice: 5.00,
        isReasoning: true,
        isVision: true,
      },
      {
        id: 'gemini-2.5-flash-preview',
        name: 'Gemini 2.5 Flash Preview',
        provider: 'google',
        description: 'Next-generation fast multimodal preview model',
        contextWindow: 1000000,
        inputPrice: 0.10,
        outputPrice: 0.40,
        isReasoning: true,
        isVision: true,
      },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    tagline: 'Ultra-fast LPU inference (500+ tokens/sec)',
    iconName: 'Zap',
    brandColor: '#f55036',
    keyPlaceholder: 'gsk_...',
    keyDocsUrl: 'https://console.groq.com/keys',
    keyFormatRegex: /^gsk_[a-zA-Z0-9_\-]{20,}$/,
    keyPrefix: 'gsk_',
    requiresKey: true,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B',
        provider: 'groq',
        description: 'Meta flagship open model with lightning fast Groq speed',
        contextWindow: 128000,
        inputPrice: 0.59,
        outputPrice: 0.79,
      },
      {
        id: 'deepseek-r1-distill-llama-70b',
        name: 'DeepSeek R1 (70B Distill)',
        provider: 'groq',
        description: 'DeepSeek reasoning distilled into Llama 70B on Groq LPUs',
        contextWindow: 128000,
        inputPrice: 0.75,
        outputPrice: 0.99,
        isReasoning: true,
      },
      {
        id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B Instant',
        provider: 'groq',
        description: 'Blazing 800+ tokens/second for lightweight tasks',
        contextWindow: 128000,
        inputPrice: 0.05,
        outputPrice: 0.08,
      },
      {
        id: 'mixtral-8x7b-32768',
        name: 'Mixtral 8x7B',
        provider: 'groq',
        description: 'MoE model with fast inference on Groq',
        contextWindow: 32768,
        inputPrice: 0.24,
        outputPrice: 0.24,
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    tagline: 'DeepSeek-V3 & DeepSeek-R1 Direct API',
    iconName: 'Compass',
    brandColor: '#4d6bfe',
    keyPlaceholder: 'sk-...',
    keyDocsUrl: 'https://platform.deepseek.com/api_keys',
    keyFormatRegex: /^sk-[a-zA-Z0-9_\-]{20,}$/,
    keyPrefix: 'sk-',
    requiresKey: true,
    defaultBaseUrl: 'https://api.deepseek.com',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek-V3 (Chat)',
        provider: 'deepseek',
        description: 'World-class 671B MoE model with exceptional coding and price',
        contextWindow: 64000,
        inputPrice: 0.14,
        outputPrice: 0.28,
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek-R1 (Reasoner)',
        provider: 'deepseek',
        description: 'State of the art open reasoning model with thought streams',
        contextWindow: 64000,
        inputPrice: 0.55,
        outputPrice: 2.19,
        isReasoning: true,
      },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    tagline: '200+ models from one unified API key',
    iconName: 'Layers',
    brandColor: '#6366f1',
    keyPlaceholder: 'sk-or-v1-...',
    keyDocsUrl: 'https://openrouter.ai/keys',
    keyFormatRegex: /^sk-or-v1-[a-zA-Z0-9_\-]{20,}$/,
    keyPrefix: 'sk-or-v1-',
    requiresKey: true,
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'deepseek/deepseek-r1',
        name: 'DeepSeek R1 (OpenRouter)',
        provider: 'openrouter',
        description: 'Full DeepSeek R1 open reasoning model',
        contextWindow: 128000,
        inputPrice: 0.55,
        outputPrice: 2.19,
        isReasoning: true,
      },
      {
        id: 'anthropic/claude-3.5-sonnet',
        name: 'Claude 3.5 Sonnet (OpenRouter)',
        provider: 'openrouter',
        description: 'Anthropic Claude 3.5 Sonnet routed via OpenRouter',
        contextWindow: 200000,
        inputPrice: 3.00,
        outputPrice: 15.00,
      },
      {
        id: 'openai/gpt-4o',
        name: 'GPT-4o (OpenRouter)',
        provider: 'openrouter',
        description: 'OpenAI GPT-4o routed via OpenRouter',
        contextWindow: 128000,
        inputPrice: 2.50,
        outputPrice: 10.00,
      },
      {
        id: 'google/gemini-2.0-flash-001',
        name: 'Gemini 2.0 Flash (OpenRouter)',
        provider: 'openrouter',
        description: 'Fast Google Gemini 2.0 Flash via OpenRouter',
        contextWindow: 1000000,
        inputPrice: 0.10,
        outputPrice: 0.40,
      },
      {
        id: 'meta-llama/llama-3.3-70b-instruct',
        name: 'Llama 3.3 70B Instruct (OpenRouter)',
        provider: 'openrouter',
        description: 'Meta open model routed through top providers',
        contextWindow: 128000,
        inputPrice: 0.12,
        outputPrice: 0.30,
      },
      {
        id: 'qwen/qwen-2.5-coder-32b-instruct',
        name: 'Qwen 2.5 Coder 32B (OpenRouter)',
        provider: 'openrouter',
        description: 'Exceptional open coding model',
        contextWindow: 128000,
        inputPrice: 0.07,
        outputPrice: 0.16,
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    tagline: 'Mistral Large, Codestral, Pixtral & Small',
    iconName: 'Flame',
    brandColor: '#ff7000',
    keyPlaceholder: 'api-key-...',
    keyDocsUrl: 'https://console.mistral.ai/api-keys',
    keyFormatRegex: /^[a-zA-Z0-9_\-]{20,}$/,
    requiresKey: true,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'mistral-large-latest',
        name: 'Mistral Large 2',
        provider: 'mistral',
        description: 'Top-tier reasoning, multilingual, and coding model',
        contextWindow: 128000,
        inputPrice: 2.00,
        outputPrice: 6.00,
      },
      {
        id: 'codestral-latest',
        name: 'Codestral',
        provider: 'mistral',
        description: 'Specialized 22B model for code generation and fill-in-the-middle',
        contextWindow: 256000,
        inputPrice: 0.20,
        outputPrice: 0.60,
      },
      {
        id: 'mistral-small-latest',
        name: 'Mistral Small',
        provider: 'mistral',
        description: 'Fast, lightweight cost-effective model',
        contextWindow: 128000,
        inputPrice: 0.20,
        outputPrice: 0.60,
      },
      {
        id: 'pixtral-12b-2409',
        name: 'Pixtral 12B',
        provider: 'mistral',
        description: 'Multimodal vision model from Mistral',
        contextWindow: 128000,
        inputPrice: 0.15,
        outputPrice: 0.15,
        isVision: true,
      },
    ],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    tagline: 'Grok 3, Grok 3 Mini, Grok 2 & Vision',
    iconName: 'Bot',
    brandColor: '#ffffff',
    keyPlaceholder: 'xai-...',
    keyDocsUrl: 'https://console.x.ai',
    keyFormatRegex: /^[a-zA-Z0-9_\-]{16,}$/,
    keyPrefix: 'xai-',
    requiresKey: true,
    defaultBaseUrl: 'https://api.x.ai/v1',
    isCustomizableBaseUrl: false,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'grok-4',
        name: 'Grok 4',
        provider: 'xai',
        description: 'Next-generation premier reasoning Grok model',
        contextWindow: 131072,
        inputPrice: 5.00,
        outputPrice: 25.00,
        isReasoning: true,
      },
      {
        id: 'grok-3',
        name: 'Grok 3',
        provider: 'xai',
        description: 'Next-generation flagship reasoning & deep problem-solving model',
        contextWindow: 131072,
        inputPrice: 3.00,
        outputPrice: 15.00,
        isReasoning: true,
      },
      {
        id: 'grok-3-mini',
        name: 'Grok 3 Mini',
        provider: 'xai',
        description: 'Ultra-fast and cost-effective Grok 3 reasoning model',
        contextWindow: 131072,
        inputPrice: 0.50,
        outputPrice: 2.00,
        isReasoning: true,
      },
      {
        id: 'grok-2',
        name: 'Grok 2',
        provider: 'xai',
        description: 'State of the art Grok reasoning and conversation model',
        contextWindow: 128000,
        inputPrice: 2.00,
        outputPrice: 10.00,
        isReasoning: true,
      },
      {
        id: 'grok-2-vision',
        name: 'Grok 2 Vision',
        provider: 'xai',
        description: 'Grok 2 with multimodal visual image comprehension',
        contextWindow: 32768,
        inputPrice: 2.00,
        outputPrice: 10.00,
        isVision: true,
        isReasoning: true,
      },
      {
        id: 'grok-beta',
        name: 'Grok Beta',
        provider: 'xai',
        description: 'Early preview Grok model',
        contextWindow: 128000,
        inputPrice: 5.00,
        outputPrice: 15.00,
      },
    ],
  },
  {
    id: 'custom',
    name: 'Custom OpenAI Endpoint',
    tagline: 'LM Studio, vLLM, Together AI, Perplexity, etc.',
    iconName: 'Sliders',
    brandColor: '#8b5cf6',
    keyPlaceholder: 'API Key (if required by endpoint)',
    keyDocsUrl: 'https://platform.openai.com/docs/api-reference',
    requiresKey: false,
    defaultBaseUrl: 'http://localhost:1234/v1',
    isCustomizableBaseUrl: true,
    directBrowserCORS: true,
    defaultModels: [
      {
        id: 'custom-model',
        name: 'Custom Model (Specify ID)',
        provider: 'custom',
        description: 'Any OpenAI-compatible completions endpoint',
        contextWindow: 32768,
        inputPrice: 0,
        outputPrice: 0,
        isCustom: true,
      },
    ],
  },
];

export const DEFAULT_SYSTEM_PROMPTS = [
  {
    id: 'general',
    title: 'Helpful & Direct (Default)',
    prompt: 'You are a helpful, brilliant, and concise AI assistant. Provide accurate, well-structured, and markdown-formatted answers. When providing code, write clean, robust code with syntax highlighting.',
  },
  {
    id: 'expert-coder',
    title: 'Senior Software Engineer',
    prompt: 'You are an elite Senior Staff Software Engineer and architect. Provide clean, idiomatic, type-safe code with clear explanations. Point out edge cases, time/space complexity, and security considerations.',
  },
  {
    id: 'concise',
    title: 'Strictly Concise',
    prompt: 'Answer questions in the minimum number of words possible while retaining total accuracy. No filler phrases, no unsolicited introductions or disclaimers.',
  },
  {
    id: 'deep-tutor',
    title: 'First-Principles Tutor',
    prompt: 'You are a passionate educator inspired by Richard Feynman. Break down complex topics using first-principles reasoning, intuitive analogies, and interactive follow-up questions.',
  },
  {
    id: 'creative-writer',
    title: 'Creative Writer & Editor',
    prompt: 'You are an acclaimed creative writer and prose stylist. Write with vivid imagery, rhythmic cadence, and nuanced emotional resonance.',
  },
];

export const CONVERSATION_STARTERS = [
  {
    title: 'Write a TypeScript API Client',
    prompt: 'Write a clean, type-safe TypeScript client for a REST API with automatic retries, abort signal support, and structured error handling.',
    tag: 'Coding',
  },
  {
    title: 'Explain Quantum Computing',
    prompt: 'Explain the difference between classical bits and quantum qubits using an intuitive coin-spinning analogy.',
    tag: 'Science',
  },
  {
    title: 'Debug & Optimize Performance',
    prompt: 'What are the top 5 performance anti-patterns in modern React 19 apps and how do you profile and fix them?',
    tag: 'Engineering',
  },
  {
    title: 'Draft a Tech Architecture RFC',
    prompt: 'Write a concise Request for Comments (RFC) template for migrating a monolithic database to a distributed event-driven architecture.',
    tag: 'Architecture',
  },
];
